/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hsbForms;

/**
 *
 * @author vignesh
 */

import hsbClasses.DbConnection;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
public class Expense extends javax.swing.JFrame {

   DbConnection db = new DbConnection();
   Connection con = db.AccessConnect();
   Main m = new Main();
   DateFormat df = new SimpleDateFormat("yyyy-MM-dd");
    public Expense() {
        initComponents();
        m.ComboBox("Select * From ExpenseType","Expense_Type",cbExp_expense_type);
        m.hsbTable(con, "Select Date,Person,Expense_Type,Name,Description,Amount,Amount_Paid,Balance,Credit From ExpenseIncome Where Category = 'Expense'", tableExpense);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane14 = new javax.swing.JScrollPane();
        tableExpense = new javax.swing.JTable();
        cbExp_expense_type = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel81 = new javax.swing.JLabel();
        dcAR_date1 = new com.toedter.calendar.JDateChooser();
        jLabel94 = new javax.swing.JLabel();
        dcAR_date2 = new com.toedter.calendar.JDateChooser();
        btnAR_select = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 153));

        tableExpense.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tableExpense.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableExpense.setRowHeight(25);
        jScrollPane14.setViewportView(tableExpense);

        cbExp_expense_type.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbExp_expense_typeActionPerformed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel33.setText("Expense Type : ");

        jLabel81.setText("From : ");

        dcAR_date1.setDateFormatString("yyyy-MM-dd");
        dcAR_date1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dcAR_date1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dcAR_date1.setOpaque(false);

        jLabel94.setText("To : ");

        dcAR_date2.setDateFormatString("yyyy-MM-dd");
        dcAR_date2.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        dcAR_date2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        dcAR_date2.setOpaque(false);

        btnAR_select.setText("SELECT");
        btnAR_select.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAR_selectActionPerformed(evt);
            }
        });

        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane14, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel33)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbExp_expense_type, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel81)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcAR_date1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel94)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dcAR_date2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnAR_select)
                        .addGap(0, 269, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbExp_expense_type, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(dcAR_date1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel81, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dcAR_date2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel94, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAR_select, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane14, javax.swing.GroupLayout.DEFAULT_SIZE, 538, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbExp_expense_typeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbExp_expense_typeActionPerformed
        if(cbExp_expense_type.getSelectedIndex() == -1)
                        {
                               m.hsbTable(con,"Select Date,Person,Expense_Type,Name,Description,Amount,Amount_Paid,Balance,Credit From ExpenseIncome Where Category = 'Expense'",tableExpense);
                            }
                        else
                        {
                            String exp = cbExp_expense_type.getSelectedItem().toString();
                            m.hsbTable(con,"Select Date,Person,Expense_Type,Name,Description,Amount,Amount_Paid,Balance,Credit From ExpenseIncome Where Category = 'Expense' AND Expense_Type = '"+exp+"'",tableExpense);
                            }
    }//GEN-LAST:event_cbExp_expense_typeActionPerformed

    private void btnAR_selectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAR_selectActionPerformed
        if(dcAR_date1.getDate() == null || dcAR_date2.getDate() == null)
        {
            JOptionPane.showMessageDialog(rootPane, "Please select date!");
        }
        else if(cbExp_expense_type.getSelectedIndex() == -1)
        {
            String d1 = df.format(dcAR_date1.getDate());
            String d2 = df.format(dcAR_date2.getDate());
            m.hsbTable(con,"Select Date,Person,Expense_Type,Name,Description,Amount,Amount_Paid,Balance,Credit From ExpenseIncome Where Category = 'Expense' AND Date BETWEEN '"+d1+"' AND '"+d2+"'",tableExpense);
        }
        else
        {
            String exp = cbExp_expense_type.getSelectedItem().toString();
            String d1 = df.format(dcAR_date1.getDate());
            String d2 = df.format(dcAR_date2.getDate());
            m.hsbTable(con,"Select Date,Person,Expense_Type,Name,Description,Amount,Amount_Paid,Balance,Credit From ExpenseIncome Where Category = 'Expense' AND Expense_Type = '"+exp+"' AND Date BETWEEN '"+d1+"' AND '"+d2+"'",tableExpense);
        }
    }//GEN-LAST:event_btnAR_selectActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
       cbExp_expense_type.setSelectedIndex(-1);
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Expense.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Expense().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAR_select;
    private javax.swing.JComboBox cbExp_expense_type;
    private com.toedter.calendar.JDateChooser dcAR_date1;
    private com.toedter.calendar.JDateChooser dcAR_date2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel81;
    private javax.swing.JLabel jLabel94;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane14;
    private javax.swing.JTable tableExpense;
    // End of variables declaration//GEN-END:variables
}
